{"name": "test_failure_handling", "status": "passed", "description": "测试失败处理（故意失败）", "steps": [{"name": "执行会失败的测试", "status": "passed", "attachments": [{"name": "状态信息", "source": "19176a7a-72f2-4ed6-89cb-7ca2c0e18861-attachment.txt", "type": "text/plain"}], "start": 1754824840867, "stop": 1754824840867}], "start": 1754824840867, "stop": 1754824840867, "uuid": "fb97a94c-cbd5-4ec7-8f93-23f53aa5bd90", "historyId": "9067154e4bc0b43c12f4e5d5bb9fb491", "testCaseId": "9067154e4bc0b43c12f4e5d5bb9fb491", "fullName": "test_conftest_fix.TestConftestFix#test_failure_handling", "labels": [{"name": "story", "value": "失败测试"}, {"name": "severity", "value": "minor"}, {"name": "feature", "value": "conftest修复验证"}, {"name": "suite", "value": "test_conftest_fix"}, {"name": "subSuite", "value": "TestConftestFix"}, {"name": "host", "value": "WIN-5FT51ARN54J"}, {"name": "thread", "value": "18896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_conftest_fix"}]}